/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-05-14 07:59:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	.brand{\r\n");
      out.write("	font-size:12px;\r\n");
      out.write("	}\r\n");
      out.write("</style>    \r\n");
      out.write(" \r\n");
      out.write("<div class=\"my-5\">\r\n");
      out.write("<h1>추천 상품</h1>\r\n");
      out.write("	<div class=\"row mb-3 justify-content-end\">\r\n");
      out.write("			<div class=\"col-6 col-md-4\">\r\n");
      out.write("				<form name=\"frm\">\r\n");
      out.write("					<div class=\"input-group\">\r\n");
      out.write("						<input class=\"form-control\" placeholder=\"검색어\" name=\"word\">\r\n");
      out.write("						<button class=\"btn btn-dark\">검색</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"div_shop\" class=\"row\"></div>\r\n");
      out.write("	<div id=\"pagination\" class=\"pagination justify-content-center mt-5\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<script id=\"temp_shop\" type=\"x-handlebars-template\">\r\n");
      out.write("	{{#each .}}\r\n");
      out.write("		<div class=\"col-2 col-md-4 col-lg-2\">\r\n");
      out.write("			<div class=\"mb-2\">\r\n");
      out.write("				<a href=\"/goods/read?gid={{gid}}\"><img src=\"{{image}}\" width=\"100%\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"brand\">{{brand}}</div>\r\n");
      out.write("			<div class=\"ellipsis\">{{{title}}}</div>\r\n");
      out.write("			<div><b>{{fmtPrice price}}원</b></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	{{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("	Handlebars.registerHelper(\"fmtPrice\", function(price){\r\n");
      out.write("		return price.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("	let size=12;\r\n");
      out.write("	let page=1;\r\n");
      out.write("	let word=\"\";\r\n");
      out.write("	//getData();\r\n");
      out.write("	getTotal();\r\n");
      out.write("	\r\n");
      out.write("	$(frm).on(\"submit\", function(e){\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		word=$(frm.word).val();\r\n");
      out.write("		//getData();\r\n");
      out.write("		page=1;\r\n");
      out.write("		getTotal();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	function getData(){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"get\",\r\n");
      out.write("			url:\"/goods/list.json\",\r\n");
      out.write("			data:{word, page, size},\r\n");
      out.write("			dataType:\"json\",\r\n");
      out.write("			success:function(data){\r\n");
      out.write("				const temp=Handlebars.compile($(\"#temp_shop\").html());\r\n");
      out.write("				$(\"#div_shop\").html(temp(data));\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	function getTotal(){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"get\",\r\n");
      out.write("			url:\"/goods/total\",\r\n");
      out.write("			data:{word},\r\n");
      out.write("			success:function(data){\r\n");
      out.write("				const total=parseInt(data);\r\n");
      out.write("				if(total==0) {\r\n");
      out.write("					alert(\"검색한 상품이 없습니다!\");\r\n");
      out.write("					return;\r\n");
      out.write("				}\r\n");
      out.write("				const totalPage=Math.ceil(total/size);\r\n");
      out.write("				$(\"#pagination\").twbsPagination(\"changeTotalPages\", totalPage, page);\r\n");
      out.write("				if(total > size){\r\n");
      out.write("					$(\"#pagination\").show();\r\n");
      out.write("				}else{\r\n");
      out.write("					$(\"#pagination\").hide();\r\n");
      out.write("				}\r\n");
      out.write("				$(\"#total\").html(\"검색수: \" + total);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	$('#pagination').twbsPagination({\r\n");
      out.write("		totalPages:10, \r\n");
      out.write("		visiblePages: 5, \r\n");
      out.write("		startPage : 1,\r\n");
      out.write("		initiateStartPageClick: false, \r\n");
      out.write("		first:'<i class=\"bi bi-chevron-double-left\"></i>', \r\n");
      out.write("		prev :'<i class=\"bi bi-chevron-left\"></i>',\r\n");
      out.write("		next :'<i class=\"bi bi-chevron-compact-right\"></i>',\r\n");
      out.write("		last :'<i class=\"bi bi-chevron-double-right\"></i>',\r\n");
      out.write("		onPageClick: function (event, clickPage) {\r\n");
      out.write("			 page=clickPage; \r\n");
      out.write("			 getData();\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
